-- Criacao das tabelas

CREATE TABLE EMPRESA (
    CNPJ VARCHAR2(20),
    NOME VARCHAR2(50) UNIQUE,
    END_CEP VARCHAR2(9),
    END_NUM VARCHAR2(3),
    END_RUA VARCHAR2(50),
    CONSTRAINT PK_CNPJ PRIMARY KEY (CNPJ)
);

CREATE TABLE CONTATOS (
    CNPJ VARCHAR2(20),
    CONTATO VARCHAR2(20),
    CONSTRAINT PK_CONTATO PRIMARY KEY (CNPJ, CONTATO),
    CONSTRAINT FK_EMP_CONT FOREIGN KEY (CNPJ) REFERENCES EMPRESA (CNPJ) ON DELETE CASCADE 
);

CREATE TABLE DIRETOR (
    CPF VARCHAR2(15),
    NOME VARCHAR2(50) NOT NULL,
    CNPJ VARCHAR2(20) NOT NULL UNIQUE,
    CONSTRAINT PK_CPF_DIR PRIMARY KEY (CPF),
    CONSTRAINT FK_DIR_EMP FOREIGN KEY (CNPJ) REFERENCES EMPRESA (CNPJ)
);

CREATE TABLE FUNCIONARIO (
    CPF VARCHAR2(15),
    NOME VARCHAR2(50) NOT NULL,
    SALARIO NUMBER NOT NULL,
    CPF_CHEFE VARCHAR2(15),
    CNPJ NOT NULL,
    CONSTRAINT PK_CPF_FUNC PRIMARY KEY (CPF),
    CONSTRAINT FK_EMP_FUNC FOREIGN KEY (CNPJ) REFERENCES EMPRESA (CNPJ)
);

CREATE TABLE MOTORISTA (
    CPF VARCHAR2(15),
    CNH VARCHAR2 NOT NULL,
    CONSTRAINT PK_CPF_MOTORISTA PRIMARY KEY (CPF),
    CONSTRAINT FK_MOTRISTA_FUNC FOREIGN KEY (CPF) REFERENCES FUNCIONARIO (CPF) ON DELETE CASCADE
);

CREATE TABLE ONIBUS (
    CHASSI VARCHAR2(17),
    CONSTRAINT PK_ONIBUS PRIMARY KEY(CHASSI)
);

CREATE TABLE VIAGEM (
    COD VARCHAR2(6),
    LINHA VARCHAR2(25) NOT NULL,
    ORIGEM VARCHAR2(25) NOT NULL,
    DESTINO VARCHAR2(25) NOT NULL,
    CONSTRAINT PK_VIAGEM PRIMARY KEY(COD)
);

CREATE TABLE CONDUZ (
    CHASSI VARCHAR2(17),
    CPF VARCHAR2(15),
    COD VARCHAR2(6),
    DATA_CONDUZ DATE,
    CONSTRAINT FK_COND_BUS FOREIGN KEY (CHASSI) REFERENCES ONIBUS(CHASSI),
    CONSTRAINT FK_COND_MOT FOREIGN KEY (CPF) REFERENCES MOTORISTA(CPF),
    CONSTRAINT FK_COND_VG FOREIGN KEY (COD) REFERENCES VIAGEM (COD),
    CONSTRAINT PK_CONDUZ PRIMARY KEY(CHASSI,CPF,COD,DATA_CONDUZ)
);

CREATE TABLE MANUTENCAO (
    CHASSI VARCHAR2(17),
    COD VARCHAR2(6),
    CONSTRAINT FK_BUS_MANU FOREIGN KEY (CHASSI) REFERENCES ONIBUS (CHASSI),
    CONSTRAINT PK_MANUTENCAO PRIMARY KEY (CHASSI,COD)
);

CREATE TABLE OFICINA (
    ID VARCHAR2(3),
    CONSTRAINT PK_OFICINA PRIMARY KEY (ID)
);

CREATE TABLE ACONTECE (
    CHASSI VARCHAR2(17),
    COD VARCHAR2(6),
    ID VARCHAR2(3),
    CONSTRAINT FK_ACON_MANU FOREIGN KEY (CHASSI, COD) REFERENCES MANUTENCAO(CHASSI, COD),
    CONSTRAINT FK_ACON_OFC FOREIGN KEY (ID) REFERENCES OFICINA(ID),
    CONSTRAINT PK_ACON PRIMARY KEY (CHASSI, COD, ID)
);

CREATE TABLE PASSAGEM (
    NUMERO NUMBER(3),
    DATA_EMISSAO DATE,
    PRECO NUMBER NOT NULL,
    PRECO_FINAL NUMBER NOT NULL, 
    COD VARCHAR(6) NOT NULL,
    CONSTRAINT PK_PASSAGEM PRIMARY KEY (NUMERO),
    CONSTRAINT FK_PSG_VG FOREIGN KEY (COD) REFERENCES VIAGEM (COD)
);

CREATE TABLE PASSAGEIRO (
    CPF VARCHAR(15),
    NOME VARCHAR(50) NOT NULL,
    CONSTRAINT PK_PASSAGEIRO PRIMARY KEY (CPF)
);

CREATE TABLE DESCONTO (
    ID VARCHAR2(4),
    TAXA NUMBER(2),
    CONSTRAINT PK_DESCONTO PRIMARY KEY (ID)
);

CREATE TABLE COMPRA (
    NUMERO NUMBER(3),
    CPF VARCHAR(15),
    ID VARCHAR(4),
    CONSTRAINT FK_PAS_COMPRA FOREIGN KEY (NUMERO) REFERENCES PASSAGEM (NUMERO),
    CONSTRAINT FK_PASSAGEIRO_COMP FOREIGN KEY (CPF) REFERENCES PASSAGEIRO (CPF),
    CONSTRAINT FK_DESC_COMPRA FOREIGN KEY (ID) REFERENCES DESCONTO (ID),
    CONSTRAINT PK_COMPRA PRIMARY KEY (NUMERO, CPF)
);